# Generated by Django 6.0.4 on 2026-04-25 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Servico',
        ),
    ]
