# Generated by Django 6.0.4 on 2026-04-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_agendamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
