# Generated by Django 6.0.4 on 2026-05-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servico_alter_cliente_options_delete_agendamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
